@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Sep 11 13:18:50 +0800 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_food_behav -key {Behavioral:sim_1:Functional:tb_food} -tclbatch tb_food.tcl -view E:/FPGA/Project/handwritten_digit_recognition/handwritten-digits-recognition-hls-main-bilibili/sparkroad_project-master/Snake_ZYNQ7000_My/doc/tb_food_behav.wcfg -log simulate.log"
call xsim  tb_food_behav -key {Behavioral:sim_1:Functional:tb_food} -tclbatch tb_food.tcl -view E:/FPGA/Project/handwritten_digit_recognition/handwritten-digits-recognition-hls-main-bilibili/sparkroad_project-master/Snake_ZYNQ7000_My/doc/tb_food_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
