webtalk_init -webtalk_dir E:/FPGA/Project/handwritten_digit_recognition/handwritten-digits-recognition-hls-main-bilibili/sparkroad_project-master/Snake_ZYNQ7000_My/prj/gluttonous_snake.sim/sim_1/behav/xsim/xsim.dir/tb_food_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 11 13:19:53 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "53ee4b21-4c55-497d-9a78-fb2e7908ae67" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5397c8bd632c4f8e9b631c5479be99eb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12400F" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10172_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1141901105 -regid "" -xml E:/FPGA/Project/handwritten_digit_recognition/handwritten-digits-recognition-hls-main-bilibili/sparkroad_project-master/Snake_ZYNQ7000_My/prj/gluttonous_snake.sim/sim_1/behav/xsim/xsim.dir/tb_food_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/FPGA/Project/handwritten_digit_recognition/handwritten-digits-recognition-hls-main-bilibili/sparkroad_project-master/Snake_ZYNQ7000_My/prj/gluttonous_snake.sim/sim_1/behav/xsim/xsim.dir/tb_food_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/FPGA/Project/handwritten_digit_recognition/handwritten-digits-recognition-hls-main-bilibili/sparkroad_project-master/Snake_ZYNQ7000_My/prj/gluttonous_snake.sim/sim_1/behav/xsim/xsim.dir/tb_food_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
